/* aiSummary.js - Automated Executive Summary & Report Export Module */

import { Storage } from './storage.js';
import { AIEngine } from './aiEngine.js';

export const AISummaryModule = {
  /**
   * Generates Executive Summary data object
   * @param {'weekly'|'monthly'|'quarterly'} period 
   * @returns {object} Executive Summary
   */
  generateExecutiveSummary(period = 'weekly') {
    const projects = Storage.getProjects();
    const resources = Storage.getResources();
    const customers = Storage.getCustomers();
    const timeLogs = Storage.getTimeLogs();
    const risks = Storage.getRisks();

    let completedCount = 0;
    let delayedCount = 0;
    let atRiskCount = 0;
    let totalProgress = 0;
    let totalHoursLogged = 0;
    let totalHoursRemaining = 0;

    projects.forEach(p => {
      const h = AIEngine.calculateProjectHealth(p);
      if (p.status === 'completed' || p.progress === 100) completedCount++;
      if (h.status === 'At Risk' || h.status === 'Critical') atRiskCount++;
      if (h.metrics.daysLeft === 0 && h.metrics.hoursLeft > 0) delayedCount++;

      totalProgress += (p.progress || 0);
      totalHoursRemaining += (p.hoursRemaining || 0);
    });

    timeLogs.forEach(t => {
      totalHoursLogged += (parseFloat(t.hoursLogged) || 0);
    });

    const avgCompletion = projects.length > 0 ? Math.round(totalProgress / projects.length) : 0;
    const resAnalysis = AIEngine.analyzeResources();

    const criticalRisksList = risks.filter(r => (r.impact === 'High' || r.impact === 'Critical') && r.status !== 'Mitigated');

    return {
      period: period.toUpperCase(),
      generatedAt: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' }),
      totalProjects: projects.length,
      completedCount,
      delayedCount,
      atRiskCount,
      avgCompletion,
      totalHoursLogged,
      totalHoursRemaining,
      overloadedResourcesCount: resAnalysis.overloadedCount,
      underutilizedResourcesCount: resAnalysis.underutilizedCount,
      criticalRisksCount: criticalRisksList.length,
      customersCount: customers.length,
      criticalRisksList: criticalRisksList.map(r => ({ title: r.title, impact: r.impact, mitigation: r.mitigationPlan })),
      keyTakeaway: `${completedCount} projects completed. ${atRiskCount} projects require executive focus. Overall portfolio completion sits at ${avgCompletion}%.`
    };
  },

  /**
   * Renders Executive Summary Modal
   * @param {'weekly'|'monthly'|'quarterly'} period 
   * @param {object} appInstance 
   */
  openExecutiveSummaryModal(period = 'weekly', appInstance) {
    const summary = this.generateExecutiveSummary(period);

    const html = `
      <div id="executive-summary-print-container" class="p-2 text-xs">
        
        <!-- Header Banner -->
        <div class="p-3 bg-primary text-white rounded-3 mb-3 d-flex justify-content-between align-items-center">
          <div>
            <h5 class="font-bold m-0 text-white">${summary.period} EXECUTIVE STATUS BRIEF</h5>
            <p class="text-xxs m-0 opacity-80">Generated by AI Portal Engine on ${summary.generatedAt}</p>
          </div>
          <button id="summary-pdf-export-btn" class="btn btn-sm btn-light font-bold text-primary py-1 px-3">
            <i class="fa-solid fa-file-pdf me-1"></i> Export PDF / Print
          </button>
        </div>

        <!-- Executive Key Takeaway Card -->
        <div class="p-3 border rounded-3 bg-body-tertiary mb-3">
          <h6 class="font-bold text-xs text-primary mb-1"><i class="fa-solid fa-lightbulb text-warning me-1"></i> Executive Key Takeaway</h6>
          <p class="text-xs text-secondary m-0" style="line-height: 1.5;">${summary.keyTakeaway}</p>
        </div>

        <!-- KPI Summary Cards -->
        <div class="row g-2 mb-3">
          <div class="col-6 col-md-3">
            <div class="p-2.5 border rounded-3 text-center bg-card">
              <div class="text-xxs text-secondary uppercase font-semibold">Overall Completion</div>
              <div class="font-bold text-lg text-primary">${summary.avgCompletion}%</div>
            </div>
          </div>
          <div class="col-6 col-md-3">
            <div class="p-2.5 border rounded-3 text-center bg-card">
              <div class="text-xxs text-secondary uppercase font-semibold">Projects Completed</div>
              <div class="font-bold text-lg text-success">${summary.completedCount} / ${summary.totalProjects}</div>
            </div>
          </div>
          <div class="col-6 col-md-3">
            <div class="p-2.5 border rounded-3 text-center bg-card">
              <div class="text-xxs text-secondary uppercase font-semibold">Projects At Risk</div>
              <div class="font-bold text-lg ${summary.atRiskCount > 0 ? 'text-danger' : 'text-success'}">${summary.atRiskCount}</div>
            </div>
          </div>
          <div class="col-6 col-md-3">
            <div class="p-2.5 border rounded-3 text-center bg-card">
              <div class="text-xxs text-secondary uppercase font-semibold">Hours Logged</div>
              <div class="font-bold text-lg text-info">${summary.totalHoursLogged} hrs</div>
            </div>
          </div>
        </div>

        <!-- Major Risks Section -->
        <div class="mb-3">
          <h6 class="font-bold text-xs text-secondary uppercase tracking-wider mb-2">Major Unmitigated Risks (${summary.criticalRisksCount})</h6>
          ${summary.criticalRisksList.length > 0 ? `
            <div class="list-group">
              ${summary.criticalRisksList.map(r => `
                <div class="list-group-item p-2 d-flex justify-content-between align-items-center">
                  <div>
                    <span class="font-bold text-primary text-xs me-2">${r.title}</span>
                    <span class="text-xxs text-muted">Mitigation: ${r.mitigation || 'In progress'}</span>
                  </div>
                  <span class="badge bg-danger-subtle text-danger border border-danger-subtle">${r.impact}</span>
                </div>
              `).join('')}
            </div>
          ` : `
            <p class="text-muted text-xs italic">No critical unmitigated risks reported.</p>
          `}
        </div>

      </div>
    `;

    appInstance.openModal(`${period.toUpperCase()} Executive Summary Report`, html, () => {
      appInstance.showToast('Executive Summary generated successfully', 'success');
    });

    // Attach PDF / Print handler
    setTimeout(() => {
      const printBtn = document.getElementById('summary-pdf-export-btn');
      if (printBtn) {
        printBtn.addEventListener('click', () => {
          window.print();
        });
      }
    }, 100);
  }
};
