/* aiSummary.js - AI Executive Summary Report (V2 server-backed, Sprint 13) & Report Export */

import { AiAssistantService } from './services/aiAssistantService.js';

/**
 * Sprint 13: the executive summary is generated by POST /api/v1/ai/report.
 * The server builds the figures from the caller's authorised AI context and
 * asks the configured provider for the narrative (Gemini, or the offline rules
 * engine). The browser sends only the period and renders the answer as text.
 * No local project data is used, so the report never mixes in unsynchronised
 * browser records.
 */

const escapeReport = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => (
  { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
));

const PERIODS = ['weekly', 'monthly', 'quarterly'];

const describeReportError = (err) => {
  const status = err && err.status;
  if (status === 401) return 'Your session has ended. Please sign in again.';
  if (status === 403) return 'Your role cannot generate the AI executive report.';
  if (status === 429) return (err && err.message) || 'Too many AI requests. Try again shortly.';
  return 'The AI executive report is unavailable right now. Try again shortly.';
};

let reportSequence = 0;

export const AISummaryModule = {
  /**
   * Renders the Executive Summary modal from the V2 AI report.
   * @param {'weekly'|'monthly'|'quarterly'} period
   * @param {object} appInstance
   */
  openExecutiveSummaryModal(period = 'weekly', appInstance) {
    const safePeriod = PERIODS.includes(period) ? period : 'weekly';
    const token = String(++reportSequence);

    const html = `
      <div id="executive-summary-print-container" class="p-2 text-xs" data-report-token="${token}">
        <div class="p-3 bg-primary text-white rounded-3 mb-3 d-flex justify-content-between align-items-center">
          <div>
            <h5 class="font-bold m-0 text-white">${escapeReport(safePeriod.toUpperCase())} EXECUTIVE STATUS BRIEF</h5>
            <p class="text-xxs m-0 opacity-80" id="executive-summary-generated">Generating from server data…</p>
          </div>
          <button id="summary-pdf-export-btn" class="btn btn-sm btn-light font-bold text-primary py-1 px-3" disabled>
            <i class="fa-solid fa-file-pdf me-1"></i> Export PDF / Print
          </button>
        </div>
        <div id="executive-summary-content" aria-live="polite">
          <div class="text-muted py-3 text-center" role="status"><i class="fa-solid fa-spinner fa-spin me-2"></i>Generating the AI executive report…</div>
        </div>
      </div>
    `;

    appInstance.openModal(`${safePeriod.toUpperCase()} Executive Summary Report`, html, () => {
      appInstance.showToast('Executive Summary generated successfully', 'success');
    });

    setTimeout(() => {
      const printBtn = document.getElementById('summary-pdf-export-btn');
      if (printBtn) {
        printBtn.addEventListener('click', () => {
          window.print();
        });
      }
    }, 100);

    this.loadReport(safePeriod, token);
  },

  /** Fetches the V2 report and renders it into the still-open modal. */
  async loadReport(period, token) {
    const isCurrent = () => document.getElementById('executive-summary-print-container')?.dataset.reportToken === token;
    let report;
    try {
      report = await AiAssistantService.executiveReport(period);
    } catch (err) {
      if (!isCurrent()) return;
      document.getElementById('executive-summary-content').innerHTML =
        `<p class="text-danger small mb-0" role="alert"><i class="fa-solid fa-circle-exclamation me-1"></i>${escapeReport(describeReportError(err))}</p>`;
      document.getElementById('executive-summary-generated').textContent = 'Report not generated';
      return;
    }
    if (!isCurrent()) return;
    this.renderReport(report);
  },

  renderReport(report) {
    const f = report.figures || {};
    const attention = Array.isArray(f.attentionProjects) ? f.attentionProjects : [];
    const providerLabel = report.provider === 'gemini' ? 'Gemini' : 'the offline rules engine';
    const generated = new Date(report.generatedAt || Date.now()).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
    document.getElementById('executive-summary-generated').textContent = `Generated by ${providerLabel} on ${generated}`;
    const printBtn = document.getElementById('summary-pdf-export-btn');
    if (printBtn) printBtn.disabled = false;

    const kpi = (label, value, tone = 'text-primary') => `
      <div class="col-6 col-md-3">
        <div class="p-2.5 border rounded-3 text-center bg-card">
          <div class="text-xxs text-secondary uppercase font-semibold">${escapeReport(label)}</div>
          <div class="font-bold text-lg ${tone}">${escapeReport(value)}</div>
        </div>
      </div>`;
    const g = f.governance;

    document.getElementById('executive-summary-content').innerHTML = `
      <div class="p-3 border rounded-3 bg-body-tertiary mb-3">
        <h6 class="font-bold text-xs text-primary mb-1"><i class="fa-solid fa-lightbulb text-warning me-1"></i> Executive Key Takeaway</h6>
        <p class="text-xs text-secondary m-0" style="line-height: 1.5; white-space: pre-wrap;">${escapeReport(report.narrative)}</p>
      </div>

      <div class="row g-2 mb-3">
        ${kpi('Average Progress', typeof f.averageProgress === 'number' ? `${f.averageProgress}%` : '—')}
        ${kpi('Projects Completed', `${f.completedProjects ?? 0} / ${f.projectsIncluded ?? 0}`, 'text-success')}
        ${kpi('Need Attention', attention.length, attention.length > 0 ? 'text-danger' : 'text-success')}
        ${kpi('Projects Reviewed', `${f.projectsIncluded ?? 0} of ${f.projectsInScope ?? 0}`, 'text-info')}
      </div>

      <div class="mb-3">
        <h6 class="font-bold text-xs text-secondary uppercase tracking-wider mb-2">Projects Needing Attention (${escapeReport(attention.length)})</h6>
        ${attention.length > 0 ? `
          <div class="list-group">
            ${attention.map((a) => `
              <div class="list-group-item p-2 d-flex justify-content-between align-items-center">
                <div>
                  <span class="font-bold text-primary text-xs me-2">${escapeReport(a.name)}</span>
                  <span class="text-xxs text-muted">${escapeReport(a.code)}${a.topFactors && a.topFactors.length ? ` · ${escapeReport(a.topFactors.join(', '))}` : ''}</span>
                </div>
                <span class="badge bg-danger-subtle text-danger border border-danger-subtle">${escapeReport(a.band)} · ${escapeReport(a.score)}/100</span>
              </div>`).join('')}
          </div>
        ` : '<p class="text-muted text-xs italic">No reviewed project is At Risk or Critical.</p>'}
      </div>

      ${g ? `
      <div class="mb-3">
        <h6 class="font-bold text-xs text-secondary uppercase tracking-wider mb-2">Governance (record counts)</h6>
        <div class="d-flex flex-wrap gap-2">
          <span class="badge bg-light text-dark border">Open risks: ${escapeReport(g.openRisks)}</span>
          <span class="badge bg-light text-dark border">High / critical risks: ${escapeReport(g.criticalOrHighRisks)}</span>
          <span class="badge bg-light text-dark border">Open issues: ${escapeReport(g.openIssues)}</span>
          <span class="badge bg-light text-dark border">Blocked dependencies: ${escapeReport(g.blockedDependencies)}</span>
        </div>
      </div>` : ''}

      <p class="text-xxs text-muted mb-0">Figures are calculated on the server from the projects in your AI scope${report.meta && report.meta.truncated ? '; the AI context is capped, so not every project is included' : ''}. The narrative is AI-generated and can be wrong.</p>
    `;
  },
};
