import { Router } from 'express';
import { healthRoutes } from './healthRoutes';
import { authRoutes } from './authRoutes';
import { userRoutes } from './userRoutes';
import { teamRoutes } from './teamRoutes';
import { productRoutes } from './productRoutes';
import { projectRoutes } from './projectRoutes';
import { portfolioRoutes } from './portfolioRoutes';
import { goalRoutes } from './goalRoutes';
import { activityRoutes } from './activityRoutes';
import { notificationRoutes } from './notificationRoutes';
import { aiRoutes } from './aiRoutes';
import { deliveryRoutes } from './deliveryRoutes';
import { sprintRoutes } from './sprintRoutes';
import { backlogRoutes } from './backlogRoutes';
import { velocityRoutes } from './velocityRoutes';
import { myWorkRoutes } from './myWorkRoutes';
import { riskRoutes } from './riskRoutes';
import { issueRoutes } from './issueRoutes';
import { dependencyRoutes } from './dependencyRoutes';
import { milestoneRoutes } from './milestoneRoutes';
import { releaseRoutes } from './releaseRoutes';
import { governanceRoutes } from './governanceRoutes';

export const v1ApiRouter = Router();

v1ApiRouter.use(healthRoutes);
v1ApiRouter.use(authRoutes);
v1ApiRouter.use(userRoutes);
v1ApiRouter.use(teamRoutes);
v1ApiRouter.use(portfolioRoutes);
v1ApiRouter.use(productRoutes);
v1ApiRouter.use(projectRoutes);
v1ApiRouter.use(deliveryRoutes);
v1ApiRouter.use(sprintRoutes);
v1ApiRouter.use(backlogRoutes);
v1ApiRouter.use(velocityRoutes);
v1ApiRouter.use(myWorkRoutes);
v1ApiRouter.use(goalRoutes);
v1ApiRouter.use(riskRoutes);
v1ApiRouter.use(issueRoutes);
v1ApiRouter.use(dependencyRoutes);
v1ApiRouter.use(milestoneRoutes);
v1ApiRouter.use(releaseRoutes);
v1ApiRouter.use(governanceRoutes);
v1ApiRouter.use(activityRoutes);
v1ApiRouter.use(notificationRoutes);
v1ApiRouter.use(aiRoutes);

