import { Project, SafeUser, UserRole } from '../models/types';
import { ProjectRepository } from '../repositories/projectRepository';
import { UserRepository } from '../repositories/userRepository';
import { TeamRepository } from '../repositories/teamRepository';
import { EpicRepository } from '../repositories/epicRepository';
import { FeatureRepository } from '../repositories/featureRepository';
import { StoryRepository } from '../repositories/storyRepository';
import { TaskRepository } from '../repositories/taskRepository';
import { applyJiraReference } from './jiraReference';
import { normaliseCriteria, normaliseUserStory, readUserStory } from './storyDetails';
import { forbidden, httpError, validationError } from './followThroughSupport';

/**
 * Sprint 16 — server-side guards for project and delivery writes.
 *
 * - Identity: ids and codes are generated by the server; a client can never
 *   choose (and so never overwrite) an authoritative record id.
 * - Access: writing a project's delivery records needs project write access
 *   — admins, or the project's manager or a listed member. Assigned work does
 *   NOT count, so an assignment can never create the access needed to make it.
 *   The one exception is an assignee changing only the status of their own
 *   story, task or subtask.
 * - Fields: each entity has an explicit editable-field allowlist; ids, codes,
 *   projectId, progress (owned by the rollups), audit and display fields are
 *   server-controlled. projectId is immutable.
 * - Values: status, priority and health use the vocabulary the application
 *   already uses; people must be existing active users; parents must belong
 *   to the same project.
 */

type Actor = Pick<SafeUser, 'id' | 'role'>;
export type DeliveryKind = 'epic' | 'feature' | 'story' | 'task' | 'subtask';

/** DeliveryStatus, plus the values the existing forms already send (planning, todo, review, completed, on-hold). */
export const DELIVERY_STATUSES = [
  'backlog', 'planned', 'ready', 'in-progress', 'blocked', 'in-review', 'testing', 'done', 'cancelled',
  'planning', 'todo', 'review', 'completed', 'on-hold',
] as const;
export const DELIVERY_PRIORITIES = ['critical', 'high', 'medium', 'low'] as const;
export const DELIVERY_HEALTH = ['on-track', 'at-risk', 'critical'] as const;

/** Fields a client may set. Everything else in a request body is ignored. */
export const DELIVERY_EDITABLE_FIELDS: Record<DeliveryKind, readonly string[]> = {
  epic: ['name', 'description', 'status', 'priority', 'health', 'ownerId', 'teamId', 'productId', 'portfolioId', 'startDate', 'targetDate', 'targetRelease', 'isArchived', 'jiraKey', 'jiraUrl'],
  feature: ['name', 'description', 'epicId', 'status', 'priority', 'ownerId', 'teamId', 'productId', 'targetRelease', 'startDate', 'targetDate', 'complexity', 'jiraKey', 'jiraUrl'],
  story: ['title', 'description', 'userStory', 'acceptanceCriteria', 'userPersona', 'userAction', 'userBenefit', 'featureId', 'epicId', 'productId', 'storyPoints', 'priority', 'status', 'assigneeId', 'teamId', 'reporterId', 'sprint', 'sprintId', 'targetRelease', 'dueDate', 'jiraKey', 'jiraUrl'],
  task: ['title', 'description', 'storyId', 'featureId', 'epicId', 'assigneeId', 'teamId', 'status', 'priority', 'dueDate', 'estimatedEffortHrs', 'actualEffortHrs', 'estimatedHours', 'spentHours', 'startDate', 'completionDate', 'sprint', 'sprintId'],
  subtask: ['taskId', 'title', 'assigneeId', 'status', 'priority', 'estimateHrs', 'dueDate'],
};

/** Delivery write roles per route, mirrored here so a direct service call is held to the same rule. */
const WRITE_ROLES: UserRole[] = ['admin', 'project-manager', 'product-manager', 'team-member'];

/** Project write access: admins, or the project's manager or a listed member. Assigned work does not count. */
export function canWriteProject(actor: Actor, project: Project | null | undefined): boolean {
  if (!project) return false;
  if (actor.role === 'admin') return true;
  if (!WRITE_ROLES.includes(actor.role)) return false;
  if (project.managerId && project.managerId === actor.id) return true;
  return (project.members || []).some((m) => m && m.userId === actor.id);
}

const conflict = (message: string) => httpError(409, 'CONFLICT', message);
const notFound = (message: string) => httpError(404, 'NOT_FOUND', message);

function pick(body: Record<string, unknown>, allowed: readonly string[]): Record<string, any> {
  const out: Record<string, any> = {};
  for (const field of allowed) {
    if (Object.prototype.hasOwnProperty.call(body, field) && body[field] !== undefined) out[field] = body[field];
  }
  return out;
}

const blank = (v: unknown) => v === null || v === '';

function text(value: unknown, field: string, max: number, required = false): string | undefined {
  if (blank(value)) {
    if (required) throw validationError(`Field '${field}' cannot be empty.`);
    return '';
  }
  if (typeof value !== 'string') throw validationError(`Field '${field}' must be a string.`);
  const trimmed = value.trim();
  if (required && !trimmed) throw validationError(`Field '${field}' cannot be empty.`);
  if (trimmed.length > max) throw validationError(`Field '${field}' must be at most ${max} characters.`);
  return trimmed;
}

function oneOf(value: unknown, allowed: readonly string[], field: string): string {
  if (typeof value !== 'string' || !allowed.includes(value)) {
    throw validationError(`Field '${field}' must be one of: ${allowed.join(', ')}.`);
  }
  return value;
}

function number(value: unknown, field: string, min: number, max: number, integer = false): number {
  const n = typeof value === 'string' && value.trim() !== '' ? Number(value) : value;
  if (typeof n !== 'number' || !Number.isFinite(n) || n < min || n > max || (integer && !Number.isInteger(n))) {
    throw validationError(`Field '${field}' must be ${integer ? 'a whole number' : 'a number'} between ${min} and ${max}.`);
  }
  return n;
}

function date(value: unknown, field: string): string | undefined {
  if (blank(value)) return undefined;
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}/.test(value) || Number.isNaN(new Date(value).getTime())) {
    throw validationError(`Field '${field}' must be a date (YYYY-MM-DD).`);
  }
  return value.slice(0, 10);
}

/** A person named on a record must be an existing, active user. '' / null clears. */
async function activeUser(value: unknown, field: string): Promise<string | undefined> {
  if (blank(value)) return undefined;
  if (typeof value !== 'string') throw validationError(`Field '${field}' must be a user id.`);
  const user = await UserRepository.findById(value);
  if (!user) throw validationError(`Field '${field}' does not match a user.`);
  if (!user.isActive) throw validationError(`Field '${field}' refers to a deactivated user.`);
  return user.id;
}

async function team(value: unknown): Promise<string | undefined> {
  if (blank(value)) return undefined;
  if (typeof value !== 'string' || !(await TeamRepository.findById(value))) throw validationError("Field 'teamId' does not match a team.");
  return value;
}

/** A parent record must exist in the same project; '' / null clears (except where required). */
async function parent(kind: 'epic' | 'feature' | 'story' | 'task', value: unknown, projectId: string, field: string, required = false): Promise<string | undefined> {
  if (blank(value)) {
    if (required) throw validationError(`Field '${field}' is required.`);
    return undefined;
  }
  if (typeof value !== 'string') throw validationError(`Field '${field}' must be an id.`);
  const repo: any = { epic: EpicRepository, feature: FeatureRepository, story: StoryRepository, task: TaskRepository }[kind];
  const record = await repo.findById(value);
  if (!record || record.projectId !== projectId) {
    throw validationError(`The ${kind} referenced by '${field}' was not found in this project.`);
  }
  return record.id;
}

/** Validates the allowlisted values in place; returns the clean payload. */
async function validateFields(kind: DeliveryKind, fields: Record<string, any>, projectId: string, current: any = {}): Promise<Record<string, any>> {
  const out: Record<string, any> = {};
  const legacy: Record<string, string> = {};
  for (const [field, value] of Object.entries(fields)) {
    switch (field) {
      case 'name': case 'title': out[field] = text(value, field, 255, true); break;
      case 'description': out[field] = text(value, field, 50000); break;
      // Sprint 19: legacy flat persona fields are folded into userStory below; they are never stored themselves.
      case 'userPersona': case 'userAction': case 'userBenefit': legacy[field] = text(value, field, 2000) ?? ''; break;
      case 'targetRelease': case 'sprint': case 'sprintId': case 'productId': case 'portfolioId': out[field] = text(value, field, 100); break;
      case 'complexity': out[field] = text(value, field, 30); break;
      case 'status': out[field] = oneOf(value, DELIVERY_STATUSES, 'status'); break;
      case 'priority': out[field] = oneOf(value, DELIVERY_PRIORITIES, 'priority'); break;
      case 'health': out[field] = oneOf(value, DELIVERY_HEALTH, 'health'); break;
      case 'ownerId': case 'assigneeId': case 'reporterId': out[field] = await activeUser(value, field); break;
      case 'teamId': out[field] = await team(value); break;
      case 'startDate': case 'targetDate': case 'dueDate': case 'completionDate': out[field] = date(value, field); break;
      case 'storyPoints': out[field] = number(value, field, 0, 1000, true); break;
      case 'estimatedEffortHrs': case 'actualEffortHrs': case 'estimateHrs': case 'estimatedHours': case 'spentHours': out[field] = number(value, field, 0, 100000); break;
      case 'isArchived':
        if (typeof value !== 'boolean') throw validationError("Field 'isArchived' must be true or false.");
        out[field] = value;
        break;
      case 'epicId': out[field] = await parent('epic', value, projectId, field); break;
      case 'featureId': out[field] = await parent('feature', value, projectId, field); break;
      case 'storyId': out[field] = await parent('story', value, projectId, field); break;
      case 'taskId': out[field] = await parent('task', value, projectId, field, true); break;
      // Sprint 19: canonical story details (storyDetails.ts).
      case 'acceptanceCriteria': out[field] = normaliseCriteria(value, validationError); break;
      case 'userStory': out[field] = normaliseUserStory(value, validationError); break;
      case 'jiraKey': case 'jiraUrl': out[field] = value; break;
      default: break;
    }
  }
  // Legacy flat values only fill a userStory the request did not send itself.
  if (Object.keys(legacy).length && out.userStory === undefined) {
    const base = readUserStory(current.userStory, current);
    out.userStory = normaliseUserStory({
      asA: legacy.userPersona ?? base.asA, iWant: legacy.userAction ?? base.iWant, soThat: legacy.userBenefit ?? base.soThat,
    }, validationError);
  }
  // Jira references keep their Sprint 15A rules (epic, feature and story only).
  if (kind === 'epic' || kind === 'feature' || kind === 'story') applyJiraReference(out, current);
  return out;
}

/** The project a delivery record belongs to (a subtask through its task). */
async function projectOf(kind: DeliveryKind, record: any): Promise<Project | null> {
  if (kind === 'subtask') {
    const task = record?.taskId ? await TaskRepository.findById(record.taskId) : null;
    return task ? ProjectRepository.findById(task.projectId) : null;
  }
  return record?.projectId ? ProjectRepository.findById(record.projectId) : null;
}

export const DeliveryGuards = {
  /**
   * Validates a create request and returns the fields to use. The caller then
   * generates the id and code; neither is ever taken from the client.
   */
  async prepareCreate(kind: DeliveryKind, body: Record<string, any>, actor: Actor): Promise<Record<string, any>> {
    const input = body && typeof body === 'object' ? body : {};
    let project: Project | null;
    if (kind === 'subtask') {
      if (blank(input.taskId) || typeof input.taskId !== 'string') throw validationError("Field 'taskId' is required.");
      const task = await TaskRepository.findById(input.taskId);
      if (!task) throw notFound('Task not found.');
      project = await ProjectRepository.findById(task.projectId);
    } else {
      if (blank(input.projectId) || typeof input.projectId !== 'string') throw validationError("Field 'projectId' is required.");
      project = await ProjectRepository.findById(input.projectId);
      if (!project) throw notFound('Project not found.');
    }
    if (!project) throw notFound('Project not found.');
    if (!canWriteProject(actor, project)) {
      throw forbidden('You can only add delivery work to projects you manage or are a member of.');
    }
    const clean = await validateFields(kind, pick(input, DELIVERY_EDITABLE_FIELDS[kind]), project.id);
    if (kind !== 'subtask') clean.projectId = project.id;
    else clean.taskId = clean.taskId || input.taskId;
    return clean;
  },

  /**
   * Validates an update against the stored record: access, immutable
   * projectId, allowlisted fields and values. Nothing is applied when any
   * check fails.
   */
  async prepareUpdate(kind: DeliveryKind, existing: any, body: Record<string, any>, actor: Actor): Promise<Record<string, any>> {
    const input = body && typeof body === 'object' ? body : {};
    if (kind !== 'subtask' && input.projectId !== undefined && input.projectId !== existing.projectId) {
      throw validationError('A delivery record cannot be moved to another project.');
    }
    const project = await projectOf(kind, existing);
    const fields = pick(input, DELIVERY_EDITABLE_FIELDS[kind]);
    if (!canWriteProject(actor, project)) {
      const isAssignee = kind !== 'epic' && kind !== 'feature' && !!existing.assigneeId && existing.assigneeId === actor.id;
      const statusOnly = Object.keys(fields).every((f) => f === 'status');
      if (!isAssignee || !statusOnly) {
        throw forbidden('You can only change delivery work in projects you manage or are a member of (assignees may change the status of their own items).');
      }
    }
    return validateFields(kind, fields, project ? project.id : existing.projectId, existing);
  },

  async assertCanDelete(kind: DeliveryKind, existing: any, actor: Actor): Promise<void> {
    if (!canWriteProject(actor, await projectOf(kind, existing))) {
      throw forbidden('You can only delete delivery work in projects you manage or are a member of.');
    }
  },

  /** Status change from My Work: the assignee, or someone with project write access, and a known status. */
  async assertStatusChange(kind: 'story' | 'task' | 'subtask', existing: any, status: unknown, actor: Actor): Promise<string> {
    const value = oneOf(status, DELIVERY_STATUSES, 'status');
    const isAssignee = !!existing.assigneeId && existing.assigneeId === actor.id;
    if (!isAssignee && !canWriteProject(actor, await projectOf(kind, existing))) {
      throw forbidden('Only the assignee or a member of the project can change this status.');
    }
    return value;
  },

  /** Repository backstop: an id already in use is never overwritten. */
  conflict,
};
